In [1]:
import numpy as np
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [2]:
def mae(y_predicted, y_true):
    total_error= 0
    for yt, yp in zip(y_predicted, y_true):
        print(yt, yp)

In [3]:
mae(y_predicted, y_true)

1 0.3
1 0.7
0 1.0
0 0.0
1 0.5


# Mean Absolute Error

In [4]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [5]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

In [6]:
# absolute difference
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [7]:
# mean absolute error
np.mean(np.abs(y_predicted - y_true))

0.5

In [8]:
#total error
np.sum(np.abs(y_predicted - y_true))

2.5

# Log Loss

In [10]:
epsilon = 1e-15

In [11]:
y_predicted

array([1, 1, 0, 0, 1])

In [12]:
# convert 0 to nearly 0
y_predicted_new= [max(i, epsilon) for i in y_predicted]
print(y_predicted_new)

[1, 1, 1e-15, 1e-15, 1]


In [13]:
# convert 1 to nearly 1
y_predicted_new= [min(i, 1-epsilon) for i in y_predicted_new]
print(y_predicted_new)

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]


In [14]:
# converting y_predicted_new to array
y_predicted_new= np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [15]:
# log 0 is infinite so converted to nearly 0 and 1
np.log(y_predicted)

C:\Users\Abdullah\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([  0.,   0., -inf, -inf,   0.])

In [16]:
# log loss formulae
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [17]:
# log loss function
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [18]:
log_loss(y_true, y_predicted)

17.2696280766844