In [1]:
import tensorflow as tf

### Constants

In [2]:
# Constants
t1 = tf.constant([1.5, 2.5, 3.5])
t1

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.5, 2.5, 3.5], dtype=float32)>

In [3]:
# 2X2 matrix
t2 = tf.constant([['b', 'b'], ['b', 'b']])
t2

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'b', b'b'],
       [b'b', b'b']], dtype=object)>

In [4]:
# sequence
lin_tensor = tf.linspace(5., 9., 5)
lin_tensor

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([5., 6., 7., 8., 9.], dtype=float32)>

In [5]:
# delta is step
range_tensor = tf.range(3., 7., delta=0.5) 
range_tensor

<tf.Tensor: shape=(8,), dtype=float32, numpy=array([3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5], dtype=float32)>

### Random Variable

In [7]:
# random variables
# it creates list of 10 random float numbers
rnd_ints = tf.random.normal([10], dtype=tf.float64)
rnd_ints

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([-0.61943942, -0.80614762,  0.19821691,  0.59505452,  0.31379991,
       -0.59993726, -0.72606807,  0.27729072,  2.10666175, -0.59038219])>

In [8]:
# it create uniform distributed list of 10 elements
rnd_uni = tf.random.uniform([10], dtype=tf.float64)
rnd_uni

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.49486626, 0.17931046, 0.79922438, 0.01079607, 0.98561248,
       0.52362995, 0.32327766, 0.01991511, 0.66750086, 0.28640911])>

In [11]:
# it shuffle constant
shuffle= tf.constant([2,3,4,5,6,7,8,9,10])
rnd_shfl= tf.random.shuffle(shuffle)
rnd_shfl

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 7,  4, 10,  5,  6,  9,  3,  2,  8])>

In [13]:
# and Variable too
shuffle= tf.Variable([2,3,4,5,6,7,8,9,10])
rnd_shfl= tf.random.shuffle(shuffle)
rnd_shfl

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 4,  6, 10,  5,  7,  2,  9,  3,  8])>

### Variable

In [2]:
# tensorA copied to variableA
tensorA = tf.constant([1.5, 2.5, 3.5])
variableA = tf.Variable(tensorA)
print(tensorA)
print(variableA)

tf.Tensor([1.5 2.5 3.5], shape=(3,), dtype=float32)
<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1.5, 2.5, 3.5], dtype=float32)>


In [5]:
# creating random variable
variableB = tf.Variable(tf.random.normal([3]))
variableB

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([-1.7708229 , -1.7962883 , -0.52644116], dtype=float32)>

In [16]:
# operation on tensor
x= tf.Variable([5.])
m = tf.Variable(tf.random.normal([]))
b = tf.Variable(tf.random.normal([]))

model = tf.add(tf.multiply(x, m), b)
loss = tf.reduce_mean(tf.pow(model, 2))

print(model)
print(loss)

tf.Tensor([-6.0402393], shape=(1,), dtype=float32)
tf.Tensor(36.48449, shape=(), dtype=float32)


### Transform tensor dimension

In [14]:
# transform array dimension
vec = tf.constant([1., 2., 3., 4.])
mat = tf.reshape(vec, [2, 2])
print(vec)
print()
print(mat)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [22]:
# reversing matrix row and column wise
mat = tf.constant([[1., 2., 3.], [4., 5., 6.]])
rev_row_wise = tf.reverse(mat, [0])
rev_col_wise = tf.reverse(mat, [1])

print(rev_row_wise)
print()
print(rev_col_wise)

tf.Tensor(
[[4. 5. 6.]
 [1. 2. 3.]], shape=(2, 3), dtype=float32)

tf.Tensor(
[[3. 2. 1.]
 [6. 5. 4.]], shape=(2, 3), dtype=float32)


In [28]:
# slice extract sub-tensor from tensors
mat = tf.constant([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
slice_mat = tf.slice(mat, [1, 1], [2, 2])
print(mat)
print()
print(slice_mat)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)

tf.Tensor(
[[5. 6.]
 [8. 9.]], shape=(2, 2), dtype=float32)


In [30]:
# stack place 1 matrix over another
t1 = tf.constant([1., 2., 7.])
t2 = tf.constant([3., 4., 8.])
t3 = tf.constant([5., 6., 9.])
t4 = tf.stack([t1, t2, t3])
t4

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 7.],
       [3., 4., 8.],
       [5., 6., 9.]], dtype=float32)>

### Math operation

In [31]:
a = tf.constant([3., 3., 3.])
b = tf.constant([2., 2., 2.])

sum = tf.add(a, b) 
diff = tf.subtract(a, b)
prod = tf.multiply(a, b)
quot = tf.divide(a, b) 

print('Sum: ', sum)
print('SUbstract: ', diff)
print('Multiply: ', prod)
print('Divide: ', quot)

Sum:  tf.Tensor([5. 5. 5.], shape=(3,), dtype=float32)
SUbstract:  tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
Multiply:  tf.Tensor([6. 6. 6.], shape=(3,), dtype=float32)
Divide:  tf.Tensor([1.5 1.5 1.5], shape=(3,), dtype=float32)


In [36]:
# dividing tensor normally and flooe wise
a = tf.constant([3, 3, 3])
b = tf.constant([2, 2, 2])

div1 = tf.divide(a, b) 
div2 = a / b 
div3 = tf.math.floordiv(a, b) 
div4 = a // b 

print('Normal divide', div1)
print('Normal divide',div2)
print('Floor divide',div3)
print('Floor divide',div4)

tf.Tensor([1.5 1.5 1.5], shape=(3,), dtype=float64)
tf.Tensor([1.5 1.5 1.5], shape=(3,), dtype=float64)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)


### Round & comparision 

In [40]:
t = tf.constant([-6.2, -3.4, 3.5, 3.6, 6.8, ])
r1 = tf.round(t)
r2 = tf.math.rint(t) 
r3 = tf.math.ceil(t) 
r4 = tf.floor(t) 

print(r1) # Round tensor
print(r2) # Element wise integer
print(r3) # Ceil of tensor
print(r4) # floor of tensor

tf.Tensor([-6. -3.  4.  4.  7.], shape=(5,), dtype=float32)
tf.Tensor([-6. -3.  4.  4.  7.], shape=(5,), dtype=float32)
tf.Tensor([-6. -3.  4.  4.  7.], shape=(5,), dtype=float32)
tf.Tensor([-7. -4.  3.  3.  6.], shape=(5,), dtype=float32)


In [41]:
t1 = tf.constant([0, -2, 4, 6])
t2 = tf.constant([[1, 3], [7, 2]])

r1 = tf.argmin(t1) # return minimum element of tensor
r2 = tf.argmax(t2) # return maximum element of tensor

print(r1)
print(r2)

tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor([1 0], shape=(2,), dtype=int64)


### Matrix operation

In [45]:
# dot product of 2 matrix
# multiply rows and column and add the
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
dot = tf.tensordot(t1, t2, 1)
dot

<tf.Tensor: shape=(), dtype=float32, numpy=20.0>

In [47]:
# matrix multiplication
t1 = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
t2 = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
dot = tf.matmul(t1, t2)
dot

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[22., 28.],
       [49., 64.]], dtype=float32)>

In [48]:
# matrix mul shortcut
print(t1 @ t2)

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


In [50]:
# m to transpose a matrix and multiply two matrices together
m1 = tf.constant([[1, 2], [3, 4]])
m2 = tf.constant([[5, 6], [7, 8]])

e1 = tf.einsum('ij->ji', m1) 
e2 = tf.einsum('ij,jk->ik', m1, m2)

print(m1)
print(e1)
print()
print(e2) # matrix transpose

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


### Session

In [66]:
t1 = tf.constant(9)
t2 = tf.constant(5)
with tf.compat.v1.Session() as sess:
 res1, res2 = sess.run([t1, t2])
 print(res1)
 print(res2)

9
5


In [63]:
t1 = tf.constant(7)
t2 = tf.constant(2)
with tf.compat.v1.Session() as sess:
 res = sess.run(t1 + t2)
 print(res)

9


### Interactive session

In [67]:
# Normal code
t1 = tf.constant(1.2)
t2 = tf.constant(3.5)

prod = tf.multiply(t1, t2)
with tf.compat.v1.Session() as sess:
 print("Product: ", sess.run(prod))

Product:  4.2000003


In [69]:
# Interactive session code
t1 = tf.constant(1.2)
t2 = tf.constant(3.5)

prod = tf.multiply(t1, t2)
sess = tf.compat.v1.InteractiveSession()
print("Product: ", prod.eval())

Product:  4.2000003


### Generating summary data

In [4]:
# Create operations that generate summary data
with tf.compat.v1.Session() as sess:
    a = tf.constant(2.5)
    b = tf.constant(4.5)
    total = a + b
    
    # Create operations that generate summary data
    a1= tf.compat.v1.summary.scalar("a", a)
    a2= tf.compat.v1.summary.scalar("b", b)
    a3= tf.compat.v1.summary.scalar("total", total)
    
    print(a1)
    print(a2)
    print(a3)

Tensor("a:0", shape=(), dtype=string)
Tensor("b:0", shape=(), dtype=string)
Tensor("total:0", shape=(), dtype=string)


In [10]:
# Create FileWriter
file_writer = tf.compat.v1.summary.FileWriter("log", graph=tf.compat.v1.get_default_graph())
file_writer
# error due to tensor version

RuntimeError: v1.summary.FileWriter is not compatible with eager execution. Use `tf.summary.create_file_writer`,or a `with v1.Graph().as_default():` context

In [11]:
# Execute first graph
with tf.compat.v1.Session() as sess:
    # Create tensors
    t1 = tf.constant([1.2, 2.3, 3.4, 4.5])
    t2 = tf.constant([5.6, 6.7, 7.8, 8.9])
    t3 = tf.concat([t1, t2], 0)
    t4 = tf.tensordot(t1, t2, 1)
    
    # execute session
    dot_result, summary= sess.run(t4)
    
    # write result to log
    tf.compat.v1.logging.info('Dot product result: ', dot_result)
    
    # print summary data
    file_writer.add_summary(summary)
    file_writer.flish()

TypeError: cannot unpack non-iterable numpy.float32 object