In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
# food review keyword
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

In [3]:
# labels of "reviews"
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [4]:
# one hot encoding of words
one_hot("amazing restaurant",30)

[24, 7]

In [6]:
# encoded vector for each review
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[13, 25],
 [24, 7],
 [21, 18],
 [4, 18, 17],
 [15, 20, 28],
 [5, 25],
 [1, 20, 19],
 [7, 1],
 [7, 3],
 [3, 6]]

In [7]:
# encoding all vector to same size=3
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[13, 25,  0],
       [24,  7,  0],
       [21, 18,  0],
       [ 4, 18, 17],
       [15, 20, 28],
       [ 5, 25,  0],
       [ 1, 20, 19],
       [ 7,  1,  0],
       [ 7,  3,  0],
       [ 3,  6,  0]])

In [8]:
embeded_vector_size = 5

model = Sequential()
# Embedding is keras pre-defined layer; vocab_size,embeded_vector_size,max_length is declared above
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [9]:
X = padded_reviews
y = sentiment

In [10]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 3, 5)              150       
_________________________________________________________________
flatten (Flatten)            (None, 15)                0         
_________________________________________________________________
dense (Dense)                (None, 1)                 16        
Total params: 166
Trainable params: 166
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.fit(X, y, epochs=50, verbose=1)

Epoch 1/50
1/1 [==============================] - 3s 3s/step - loss: 0.6865 - accuracy: 0.8000
Epoch 2/50
1/1 [==============================] - 0s 10ms/step - loss: 0.6850 - accuracy: 0.9000
Epoch 3/50
1/1 [==============================] - 0s 7ms/step - loss: 0.6834 - accuracy: 0.8000
Epoch 4/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6819 - accuracy: 0.8000
Epoch 5/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6803 - accuracy: 0.8000
Epoch 6/50
1/1 [==============================] - 0s 8ms/step - loss: 0.6788 - accuracy: 0.8000
Epoch 7/50
1/1 [==============================] - 0s 5ms/step - loss: 0.6772 - accuracy: 0.8000
Epoch 8/50
1/1 [==============================] - 0s 6ms/step - loss: 0.6757 - accuracy: 0.8000
Epoch 9/50
1/1 [==============================] - 0s 7ms/step - loss: 0.6741 - accuracy: 0.8000
Epoch 10/50
1/1 [==============================] - 0s 12ms/step - loss: 0.6725 - accuracy: 0.9000
Epoch 11/50
1/1 [=====================

In [13]:
model.evaluate(X, y)

1/1 [==============================] - 0s 25ms/step - loss: 0.6043 - accuracy: 0.9000


[0.6042678952217102, 0.8999999761581421]

In [16]:
# weight of reviews array
weights = model.get_layer('embedding').get_weights()[0]
weights

array([[ 0.09628446,  0.07398094,  0.0008327 ,  0.09887042,  0.0002406 ],
       [ 0.01579561,  0.03396668, -0.08388732,  0.09147494,  0.03780185],
       [-0.04040011,  0.0428051 ,  0.02637786,  0.00598715, -0.01523396],
       [ 0.06954566,  0.02686336, -0.09407169,  0.07032447,  0.04059418],
       [-0.04012604, -0.08061554,  0.07216562, -0.07886373,  0.01573459],
       [ 0.08648391,  0.00359615, -0.07307057,  0.1023572 , -0.09519064],
       [ 0.09771378, -0.00105027, -0.01141248,  0.04280407,  0.09566432],
       [ 0.06940757,  0.05927425, -0.06112317,  0.06405799, -0.06563884],
       [-0.02789155,  0.01972323,  0.02163409, -0.03454898, -0.00477271],
       [-0.02253958, -0.03831007, -0.03408853, -0.02846241,  0.01561663],
       [ 0.01470587, -0.03715972,  0.01954916,  0.03988605,  0.02630813],
       [-0.00467942, -0.04134126,  0.0290795 ,  0.00258292,  0.01818866],
       [ 0.0025645 ,  0.04636823, -0.0495425 ,  0.0220401 ,  0.00475455],
       [-0.0742823 , -0.01501617,  0.0

In [17]:
len(weights)

30

In [18]:
weights[0]

array([0.09628446, 0.07398094, 0.0008327 , 0.09887042, 0.0002406 ],
      dtype=float32)

In [19]:
weights[4]

array([-0.04012604, -0.08061554,  0.07216562, -0.07886373,  0.01573459],
      dtype=float32)

In [21]:
weights[29]

array([ 0.02554272, -0.02827921,  0.02689913, -0.01758425, -0.02362547],
      dtype=float32)